### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by half0wl** [half0wl/concode#3]
We'll most likely be using [st4lk/django-rest-social-auth](https://github.com/st4lk/django-rest-social-auth) for auth-ing with Github. I'm thinking token-based / JWT authentication would be the way to go.

@pixelasticity What do you think of this, and the [auth flow](https://github.com/st4lk/django-rest-social-auth#oauth-20-workflow-with-rest-social-auth)?

**Comment by pixelasticity** [comment]
I like the idea of JWT authentication, and I should be able to work with that auth flow. 👍

**Comment by half0wl** [comment]
Implemented by #6
