### ISSUE TITLE
Endpoints

### ISSUE THREAD

**Issue by half0wl** [half0wl/concode#4]
Authentication - not sure yet, depends on #3. Profiles will also depend on #3, and #2.

Resource `/project/`

* `GET` - List all projects
* `GET /project/<id>` - Get a specific project
* `POST` - Create a new project

**Comment by pixelasticity** [comment]
@half0wl What would endpoints look like for, say, recommended users?

**Comment by half0wl** [comment]
@pixelasticity Probably `/project/recommended_collaborators/`.

What do you think of recommended projects for users (`/user/recommended_projects/`)? This way, we only have to index either one of them (on the project, or on the user), and we can use that as a lookup for the other (e.g. recommended projects for users will contain `project_id`s, and we can fetch the list of all associated users given the `project_id`).

**Comment by pixelasticity** [comment]
That makes sense, and I can't think of a better way to do it. :1st_place_medal:

**Comment by half0wl** [comment]
Currently being worked on branch [concode/serializers-and-endpoints](https://github.com/half0wl/concode/tree/serializers-and-endpoints).
